# TASK 6

In [4]:
# Import libraries

import mysql.connector
import pandas as pd

# Connect to MySQL

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
    database="classicmodels"
)

# Create cursor

cursor = conn.cursor()

# Check connection

if conn.is_connected():
    print("Database Connected Successfully")


# Problem 1

query = """
SELECT customerName, creditLimit
FROM customers
WHERE creditLimit = (
    SELECT MAX(creditLimit)
    FROM customers
);
"""

cursor.execute(query)
result = cursor.fetchall()

for row in result:
    print(row)


# Problem 2

query = """
SELECT productName, buyPrice
FROM products
WHERE buyPrice > (
    SELECT AVG(buyPrice)
    FROM products
);
"""

cursor.execute(query)
result = cursor.fetchall()

for row in result:
    print(row)


# Problem 3

query = """
SELECT employeeNumber, firstName, lastName
FROM employees
WHERE employeeNumber IN (
    SELECT DISTINCT salesRepEmployeeNumber
    FROM customers
    WHERE salesRepEmployeeNumber IS NOT NULL
);
"""

cursor.execute(query)
result = cursor.fetchall()

for row in result:
    print(row)


# Problem 4

query = """
SELECT customerName, country
FROM customers
WHERE country IN (
    SELECT country
    FROM customers
    GROUP BY country
    HAVING COUNT(*) > 1
);
"""

cursor.execute(query)
result = cursor.fetchall()

for row in result:
    print(row)


# Problem 5

query = """
SELECT customerName, country, creditLimit
FROM customers c
WHERE creditLimit > (
    SELECT AVG(creditLimit)
    FROM customers
    WHERE country = c.country
);
"""

cursor.execute(query)
result = cursor.fetchall()

for row in result:
    print(row)


# Problem 6

query = """
SELECT c.customerName, p.amount
FROM customers c
JOIN payments p
ON c.customerNumber = p.customerNumber
WHERE p.amount = (
    SELECT MAX(amount)
    FROM payments
);
"""

cursor.execute(query)
result = cursor.fetchall()

for row in result:
    print(row)

# Problem 7

query = """
DROP TABLE IF EXISTS student_details;
"""

cursor.execute(query)

query = """
CREATE TABLE student_details (
    student_id INT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    age INT CHECK(age >= 18)
);
"""

cursor.execute(query)
conn.commit()


# Problem 8

query = """
ALTER TABLE student_details
ADD phone_number VARCHAR(15);
"""

cursor.execute(query)
conn.commit()


# Problem 9

query = """
DROP TABLE IF EXISTS department_details;
"""

cursor.execute(query)

query = """
CREATE TABLE department_details (
    department_id INT PRIMARY KEY,
    department_name VARCHAR(100),
    location VARCHAR(100)
);
"""

cursor.execute(query)

query = """
ALTER TABLE department_details
RENAME COLUMN location TO department_location;
"""

cursor.execute(query)
conn.commit()


# Problem 10

query = """
INSERT INTO student_details
VALUES
(101,'Rahul','rahul@gmail.com',20,'9876543210'),
(102,'Anita','anita@gmail.com',21,'9876543211'),
(103,'Kiran','kiran@gmail.com',22,'9876543212'),
(104,'Sneha','sneha@gmail.com',20,'9876543213'),
(105,'Arjun','arjun@gmail.com',23,'9876543214');
"""

cursor.execute(query)
conn.commit()


# Problem 11

query = """
UPDATE student_details
SET email = 'rahul_new@gmail.com'
WHERE student_id = 101;
"""

cursor.execute(query)
conn.commit()

query = "SELECT * FROM student_details"

df = pd.read_sql(query, conn)
display(df)


# Problem 12

query = """
DELETE FROM student_details
WHERE student_id = 105;
"""

cursor.execute(query)
conn.commit()

query = "SELECT * FROM student_details"

df = pd.read_sql(query, conn)
display(df)

# Close connection

cursor.close()
conn.close()

Database Connected Successfully
('Euro+ Shopping Channel', Decimal('227600.00'))
('1952 Alpine Renault 1300', Decimal('98.58'))
('1996 Moto Guzzi 1100i', Decimal('68.99'))
('2003 Harley-Davidson Eagle Drag Bike', Decimal('91.02'))
('1972 Alfa Romeo GTA', Decimal('85.68'))
('1962 LanciaA Delta 16V', Decimal('103.42'))
('1968 Ford Mustang', Decimal('95.34'))
('2001 Ferrari Enzo', Decimal('95.59'))
('1958 Setra Bus', Decimal('77.90'))
('2002 Suzuki XREO', Decimal('66.27'))
('1969 Corvair Monza', Decimal('89.14'))
('1968 Dodge Charger', Decimal('75.16'))
('1969 Ford Falcon', Decimal('83.05'))
('1957 Chevy Pickup', Decimal('55.70'))
('1969 Dodge Charger', Decimal('58.73'))
('1940 Ford Pickup Truck', Decimal('58.33'))
('1993 Mazda RX-7', Decimal('83.51'))
('1937 Lincoln Berline', Decimal('60.62'))
('1965 Aston Martin DB5', Decimal('65.96'))
('1980s Black Hawk Helicopter', Decimal('77.27'))
('1917 Grand Touring Sedan', Decimal('86.70'))
('1995 Honda Civic', Decimal('93.89'))
('1998 Chrysler Plymouth Prowler', Decimal('101.51'))
('1964 Mercedes Tour Bus', Decimal('74.86'))
('1932 Model A Ford J-Coupe', Decimal('58.48'))
('1928 Mercedes-Benz SSK', Decimal('72.56'))
('1999 Indy 500 Monte Carlo SS', Decimal('56.76'))
('1913 Ford Model T Speedster', Decimal('60.78'))
('18th Century Vintage Horse Carriage', Decimal('60.74'))
('1903 Ford Model A', Decimal('68.30'))
('1992 Ferrari 360 Spider red', Decimal('77.90'))
('1985 Toyota Supra', Decimal('57.01'))
('Collectable Wooden Train', Decimal('67.56'))
('1917 Maxwell Touring Car', Decimal('57.54'))
('1976 Ford Gran Torino', Decimal('73.49'))
('1948 Porsche Type 356 Roadster', Decimal('62.16'))
('1941 Chevrolet Special Deluxe Cabriolet', Decimal('64.58'))
('1970 Triumph Spitfire', Decimal('91.92'))
('1940s Ford truck', Decimal('84.76'))
('1957 Corvette Convertible', Decimal('69.93'))
('1997 BMW R 1100 S', Decimal('60.86'))
('1928 British Royal Navy Airplane', Decimal('66.74'))
('18th century schooner', Decimal('82.34'))
('1962 Volkswagen Microbus', Decimal('61.34'))
('1952 Citroen-15CV', Decimal('72.82'))
('2002 Chevy Corvette', Decimal('62.11'))
('1956 Porsche 356A Coupe', Decimal('98.30'))
('1992 Porsche Cayenne Turbo Silver', Decimal('69.78'))
('1936 Chrysler Airflow', Decimal('57.46'))
('1997 BMW F650 ST', Decimal('66.92'))
('1974 Ducati 350 Mk3 Desmo', Decimal('56.13'))
('Diamond T620 Semi-Skirted Tanker', Decimal('68.29'))
('America West Airlines B757-200', Decimal('68.80'))
('ATA: B757-300', Decimal('59.33'))
('F/A 18 Hornet 1/72', Decimal('54.40'))
(1165, 'Leslie', 'Jennings')
(1166, 'Leslie', 'Thompson')
(1188, 'Julie', 'Firrelli')
(1216, 'Steve', 'Patterson')
(1286, 'Foon Yue', 'Tseng')
(1323, 'George', 'Vanauf')
(1337, 'Loui', 'Bondur')
(1370, 'Gerard', 'Hernandez')
(1401, 'Pamela', 'Castillo')
(1501, 'Larry', 'Bott')
(1504, 'Barry', 'Jones')
(1611, 'Andy', 'Fixter')
(1612, 'Peter', 'Marsh')
(1621, 'Mami', 'Nishi')
(1702, 'Martin', 'Gerard')
('Atelier graphique', 'France')
('Signal Gift Stores', 'USA')
('Australian Collectors, Co.', 'Australia')
('La Rochelle Gifts', 'France')
('Mini Gifts Distributors Ltd.', 'USA')
('Blauer See Auto, Co.', 'Germany')
('Mini Wheels Co.', 'USA')
('Land of Toys Inc.', 'USA')
('Euro+ Shopping Channel', 'Spain')
('Volvo Model Replicas, Co', 'Sweden')
('Danish Wholesale Imports', 'Denmark')
('Saveley & Henriot, Co.', 'France')
('Dragon Souveniers, Ltd.', 'Singapore')
('Muscle Machine Inc', 'USA')
('Diecast Classics Inc.', 'USA')
('Technics Stores Inc.', 'USA')
('Handji Gifts& Co', 'Singapore')
('Herkku Gifts', 'Norway  ')
('American Souvenirs Inc', 'USA')
('Porto Imports Co.', 'Portugal')
('Daedalus Designs Imports', 'France')
("La Corne D'abondance, Co.", 'France')
('Cambridge Collectables Co.', 'USA')
('Gift Depot Inc.', 'USA')
('Osaka Souveniers Co.', 'Japan')
('Vitachrome Inc.', 'USA')
('Toys of Finland, Co.', 'Finland')
('AV Stores, Co.', 'UK')
('Clover Collections, Co.', 'Ireland')
('Auto-Moto Classics Inc.', 'USA')
('UK Collectables, Ltd.', 'UK')
('Canadian Gift Exchange Network', 'Canada')
('Online Mini Collectables', 'USA')
('Toys4GrownUps.com', 'USA')
('Asian Shopping Network, Co', 'Singapore')
('Mini Caravy', 'France')
('Enaco Distributors', 'Spain')
('Boards & Toys Co.', 'USA')
('Natürlich Autos', 'Germany')
('Heintze Collectables', 'Denmark')
('Québec Home Shopping Network', 'Canada')
('ANG Resellers', 'Spain')
('Collectable Mini Designs Co.', 'USA')
('giftsbymail.co.uk', 'UK')
('Alpha Cognac', 'France')
('Messner Shopping Network', 'Germany')
('Amica Models & Co.', 'Italy')
('Lyon Souveniers', 'France')
('Auto Associés & Cie.', 'France')
('Toms Spezialitäten, Ltd', 'Germany')
('Royal Canadian Collectables, Ltd.', 'Canada')
('Franken Gifts, Co', 'Germany')
("Anna's Decorations, Ltd", 'Australia')
('Rovelli Gifts', 'Italy')
('Souveniers And Things Co.', 'Australia')
("Marta's Replicas Co.", 'USA')
('BG&E Collectables', 'Switzerland')
('Vida Sport, Ltd', 'Switzerland')
('Norway Gifts By Mail, Co.', 'Norway  ')
('Der Hund Imports', 'Germany')
('Oulu Toy Supplies, Inc.', 'Finland')
('Petit Auto', 'Belgium')
('Mini Classics', 'USA')
('Mini Creations Ltd.', 'USA')
('Corporate Gift Ideas Co.', 'USA')
('Down Under Souveniers, Inc', 'New Zealand')
('Stylish Desk Decors, Co.', 'UK')
('Tekni Collectables Inc.', 'USA')
('Australian Gift Network, Co', 'Australia')
('Suominen Souveniers', 'Finland')
('Cramer Spezialitäten, Ltd', 'Germany')
('Classic Gift Ideas, Inc', 'USA')
('CAF Imports', 'Spain')
("Men 'R' US Retailers, Ltd.", 'USA')
('Asian Treasures, Inc.', 'Ireland')
('Marseille Mini Autos', 'France')
('Reims Collectables', 'France')
('GiftsForHim.com', 'New Zealand')
('Kommission Auto', 'Germany')
('Gifts4AllAges.com', 'USA')
('Online Diecast Creations Co.', 'USA')
('Lisboa Souveniers, Inc', 'Portugal')
('Precious Collectables', 'Switzerland')
('Collectables For Less Inc.', 'USA')
('Royale Belge', 'Belgium')
('Salzburg Collectables', 'Austria')
("L'ordine Souveniers", 'Italy')
('Tokyo Collectables, Ltd', 'Japan')
('Auto Canal+ Petit', 'France')
('Stuttgart Collectable Exchange', 'Germany')
('Extreme Desk Decorations, Ltd', 'New Zealand')
('Bavarian Collectables Imports, Co.', 'Germany')
('Classic Legends Inc.', 'USA')
('Feuer Online Stores, Inc', 'Germany')
('Gift Ideas Corp.', 'USA')
('Scandinavian Gift Ideas', 'Sweden')
('The Sharp Gifts Warehouse', 'USA')
('Mini Auto Werke', 'Austria')
('Super Scale Inc.', 'USA')
('Microscale Inc.', 'USA')
('Corrida Auto Replicas, Ltd', 'Spain')
('Warburg Exchange', 'Germany')
('FunGiftIdeas.com', 'USA')
('Anton Designs, Ltd.', 'Spain')
('Australian Collectables, Ltd', 'Australia')
('Frau da Collezione', 'Italy')
('West Coast Collectables Co.', 'USA')
('Mit Vergnügen & Co.', 'Germany')
('Iberia Gift Imports, Corp.', 'Spain')
('Motor Mint Distributors Inc.', 'USA')
('Signal Collectibles Ltd.', 'USA')
('Double Decker Gift Stores, Ltd', 'UK')
('Diecast Collectables', 'USA')
("Kelly's Gift Shop", 'New Zealand')
('Australian Collectors, Co.', 'Australia', Decimal('117300.00'))
('La Rochelle Gifts', 'France', Decimal('118200.00'))
('Mini Gifts Distributors Ltd.', 'USA', Decimal('210500.00'))
('Blauer See Auto, Co.', 'Germany', Decimal('59700.00'))
('Land of Toys Inc.', 'USA', Decimal('114900.00'))
('Euro+ Shopping Channel', 'Spain', Decimal('227600.00'))
('Saveley & Henriot, Co.', 'France', Decimal('123900.00'))
('Dragon Souveniers, Ltd.', 'Singapore', Decimal('103800.00'))
('Muscle Machine Inc', 'USA', Decimal('138500.00'))
('Diecast Classics Inc.', 'USA', Decimal('100600.00'))
('Technics Stores Inc.', 'USA', Decimal('84600.00'))
('Handji Gifts& Co', 'Singapore', Decimal('97900.00'))
('Herkku Gifts', 'Norway  ', Decimal('96800.00'))
('Daedalus Designs Imports', 'France', Decimal('82900.00'))
("La Corne D'abondance, Co.", 'France', Decimal('84300.00'))
('Gift Depot Inc.', 'USA', Decimal('84300.00'))
('Toys of Finland, Co.', 'Finland', Decimal('96500.00'))
('AV Stores, Co.', 'UK', Decimal('136800.00'))
('Clover Collections, Co.', 'Ireland', Decimal('69400.00'))
('UK Collectables, Ltd.', 'UK', Decimal('92700.00'))
('Canadian Gift Exchange Network', 'Canada', Decimal('90300.00'))
('Toys4GrownUps.com', 'USA', Decimal('90700.00'))
('Heintze Collectables', 'Denmark', Decimal('120800.00'))
('Collectable Mini Designs Co.', 'USA', Decimal('105000.00'))
('giftsbymail.co.uk', 'UK', Decimal('93900.00'))
('Amica Models & Co.', 'Italy', Decimal('113000.00'))
('Auto Associés & Cie.', 'France', Decimal('77900.00'))
('Toms Spezialitäten, Ltd', 'Germany', Decimal('120400.00'))
('Royal Canadian Collectables, Ltd.', 'Canada', Decimal('89600.00'))
("Anna's Decorations, Ltd", 'Australia', Decimal('107800.00'))
('Rovelli Gifts', 'Italy', Decimal('119600.00'))
('Souveniers And Things Co.', 'Australia', Decimal('93300.00'))
("Marta's Replicas Co.", 'USA', Decimal('123700.00'))
('Vida Sport, Ltd', 'Switzerland', Decimal('141300.00'))
('Petit Auto', 'Belgium', Decimal('79900.00'))
('Mini Classics', 'USA', Decimal('102700.00'))
('Mini Creations Ltd.', 'USA', Decimal('94500.00'))
('Corporate Gift Ideas Co.', 'USA', Decimal('105000.00'))
('Suominen Souveniers', 'Finland', Decimal('98800.00'))
('Classic Gift Ideas, Inc', 'USA', Decimal('81100.00'))
('Reims Collectables', 'France', Decimal('81100.00'))
('Online Diecast Creations Co.', 'USA', Decimal('114200.00'))
('Salzburg Collectables', 'Austria', Decimal('71700.00'))
("L'ordine Souveniers", 'Italy', Decimal('121400.00'))
('Tokyo Collectables, Ltd', 'Japan', Decimal('94400.00'))
('Auto Canal+ Petit', 'France', Decimal('95000.00'))
('Bavarian Collectables Imports, Co.', 'Germany', Decimal('77000.00'))
('Scandinavian Gift Ideas', 'Sweden', Decimal('116400.00'))
('Super Scale Inc.', 'USA', Decimal('95400.00'))
('Corrida Auto Replicas, Ltd', 'Spain', Decimal('104600.00'))
('FunGiftIdeas.com', 'USA', Decimal('85800.00'))
('Diecast Collectables', 'USA', Decimal('85100.00'))
("Kelly's Gift Shop", 'New Zealand', Decimal('110000.00'))
('Euro+ Shopping Channel', Decimal('120166.58'))

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\2389818216.py:226: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

   student_id   name                email  age phone_number
0         101  Rahul  rahul_new@gmail.com   20   9876543210
1         102  Anita      anita@gmail.com   21   9876543211
2         103  Kiran      kiran@gmail.com   22   9876543212
3         104  Sneha      sneha@gmail.com   20   9876543213
4         105  Arjun      arjun@gmail.com   23   9876543214

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\2389818216.py:242: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

   student_id   name                email  age phone_number
0         101  Rahul  rahul_new@gmail.com   20   9876543210
1         102  Anita      anita@gmail.com   21   9876543211
2         103  Kiran      kiran@gmail.com   22   9876543212
3         104  Sneha      sneha@gmail.com   20   9876543213

In [6]:
# Import libraries

import mysql.connector
import pandas as pd

# Connect to MySQL

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
    database="classicmodels"
)

# Create cursor

cursor = conn.cursor()

# Check connection

if conn.is_connected():
    print("Database Connected Successfully")


# Problem 1

query = """
SELECT customerName, creditLimit
FROM customers
WHERE creditLimit = (
    SELECT MAX(creditLimit)
    FROM customers
);
"""

df = pd.read_sql(query, conn)
display(df)


# Problem 2

query = """
SELECT productName, buyPrice
FROM products
WHERE buyPrice > (
    SELECT AVG(buyPrice)
    FROM products
);
"""

df = pd.read_sql(query, conn)
display(df)


# Problem 3

query = """
SELECT employeeNumber, firstName, lastName
FROM employees
WHERE employeeNumber IN (
    SELECT DISTINCT salesRepEmployeeNumber
    FROM customers
    WHERE salesRepEmployeeNumber IS NOT NULL
);
"""

df = pd.read_sql(query, conn)
display(df)


# Problem 4

query = """
SELECT customerName, country
FROM customers
WHERE country IN (
    SELECT country
    FROM customers
    GROUP BY country
    HAVING COUNT(*) > 1
);
"""

df = pd.read_sql(query, conn)
display(df)


# Problem 5

query = """
SELECT customerName, country, creditLimit
FROM customers c
WHERE creditLimit > (
    SELECT AVG(creditLimit)
    FROM customers
    WHERE country = c.country
);
"""

df = pd.read_sql(query, conn)
display(df)


# Problem 6

query = """
SELECT c.customerName, p.amount
FROM customers c
JOIN payments p
ON c.customerNumber = p.customerNumber
WHERE p.amount = (
    SELECT MAX(amount)
    FROM payments
);
"""

df = pd.read_sql(query, conn)
display(df)


# Problem 7

query = "DROP TABLE IF EXISTS student_details;"
cursor.execute(query)

query = """
CREATE TABLE student_details (
    student_id INT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    age INT CHECK(age >= 18)
);
"""

cursor.execute(query)
conn.commit()


# Problem 8

query = """
ALTER TABLE student_details
ADD phone_number VARCHAR(15);
"""

cursor.execute(query)
conn.commit()


# Problem 9

query = "DROP TABLE IF EXISTS department_details;"
cursor.execute(query)

query = """
CREATE TABLE department_details (
    department_id INT PRIMARY KEY,
    department_name VARCHAR(100),
    location VARCHAR(100)
);
"""

cursor.execute(query)

query = """
ALTER TABLE department_details
RENAME COLUMN location TO department_location;
"""

cursor.execute(query)
conn.commit()


# Problem 10

query = """
INSERT INTO student_details
VALUES
(101,'Rahul','rahul@gmail.com',20,'9876543210'),
(102,'Anita','anita@gmail.com',21,'9876543211'),
(103,'Kiran','kiran@gmail.com',22,'9876543212'),
(104,'Sneha','sneha@gmail.com',20,'9876543213'),
(105,'Arjun','arjun@gmail.com',23,'9876543214');
"""

cursor.execute(query)
conn.commit()


# Problem 11

query = """
UPDATE student_details
SET email='rahul_new@gmail.com'
WHERE student_id=101;
"""

cursor.execute(query)
conn.commit()

df = pd.read_sql("SELECT * FROM student_details;", conn)
display(df)


# Problem 12

query = """
DELETE FROM student_details
WHERE student_id=105;
"""

cursor.execute(query)
conn.commit()

df = pd.read_sql("SELECT * FROM student_details;", conn)
display(df)


# Problem 13

print("Database Connected Successfully")


# Problem 14

query = """
SELECT customerName,
       country,
       creditLimit
FROM customers;
"""

df = pd.read_sql(query, conn)
display(df.head(10))


# Problem 15

query = """
SELECT productName,
       buyPrice,
       MSRP
FROM products;
"""

df = pd.read_sql(query, conn)

df["Estimated Profit"] = df["MSRP"] - df["buyPrice"]

display(df)


# Close connection

cursor.close()
conn.close()

Database Connected Successfully

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\3187916089.py:36: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

             customerName  creditLimit
0  Euro+ Shopping Channel     227600.0

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\3187916089.py:51: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

                                productName  buyPrice
0                  1952 Alpine Renault 1300     98.58
1                     1996 Moto Guzzi 1100i     68.99
2      2003 Harley-Davidson Eagle Drag Bike     91.02
3                       1972 Alfa Romeo GTA     85.68
4                    1962 LanciaA Delta 16V    103.42
5                         1968 Ford Mustang     95.34
6                         2001 Ferrari Enzo     95.59
7                            1958 Setra Bus     77.90
8                          2002 Suzuki XREO     66.27
9                        1969 Corvair Monza     89.14
10                       1968 Dodge Charger     75.16
11                         1969 Ford Falcon     83.05
12                        1957 Chevy Pickup     55.70
13                       1969 Dodge Charger     58.73
14                   1940 Ford Pickup Truck     58.33
15                          1993 Mazda RX-7     83.51
16                     1937 Lincoln Berline     60.62
17                    1965 Aston Martin DB5     65.96
18              1980s Black Hawk Helicopter     77.27
19                 1917 Grand Touring Sedan     86.70
20                         1995 Honda Civic     93.89
21           1998 Chrysler Plymouth Prowler    101.51
22                   1964 Mercedes Tour Bus     74.86
23                1932 Model A Ford J-Coupe     58.48
24                   1928 Mercedes-Benz SSK     72.56
25             1999 Indy 500 Monte Carlo SS     56.76
26              1913 Ford Model T Speedster     60.78
27      18th Century Vintage Horse Carriage     60.74
28                        1903 Ford Model A     68.30
29              1992 Ferrari 360 Spider red     77.90
30                        1985 Toyota Supra     57.01
31                 Collectable Wooden Train     67.56
32                 1917 Maxwell Touring Car     57.54
33                    1976 Ford Gran Torino     73.49
34           1948 Porsche Type 356 Roadster     62.16
35  1941 Chevrolet Special Deluxe Cabriolet     64.58
36                    1970 Triumph Spitfire     91.92
37                         1940s Ford truck     84.76
38                1957 Corvette Convertible     69.93
39                        1997 BMW R 1100 S     60.86
40         1928 British Royal Navy Airplane     66.74
41                    18th century schooner     82.34
42                 1962 Volkswagen Microbus     61.34
43                        1952 Citroen-15CV     72.82
44                      2002 Chevy Corvette     62.11
45                  1956 Porsche 356A Coupe     98.30
46        1992 Porsche Cayenne Turbo Silver     69.78
47                    1936 Chrysler Airflow     57.46
48                         1997 BMW F650 ST     66.92
49                1974 Ducati 350 Mk3 Desmo     56.13
50         Diamond T620 Semi-Skirted Tanker     68.29
51           America West Airlines B757-200     68.80
52                            ATA: B757-300     59.33
53                       F/A 18 Hornet 1/72     54.40

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\3187916089.py:67: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

    employeeNumber firstName   lastName
0             1165    Leslie   Jennings
1             1166    Leslie   Thompson
2             1188     Julie   Firrelli
3             1216     Steve  Patterson
4             1286  Foon Yue      Tseng
5             1323    George     Vanauf
6             1337      Loui     Bondur
7             1370    Gerard  Hernandez
8             1401    Pamela   Castillo
9             1501     Larry       Bott
10            1504     Barry      Jones
11            1611      Andy     Fixter
12            1612     Peter      Marsh
13            1621      Mami      Nishi
14            1702    Martin     Gerard

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\3187916089.py:84: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

                       customerName      country
0                 Atelier graphique       France
1                Signal Gift Stores          USA
2        Australian Collectors, Co.    Australia
3                 La Rochelle Gifts       France
4      Mini Gifts Distributors Ltd.          USA
..                              ...          ...
109    Motor Mint Distributors Inc.          USA
110        Signal Collectibles Ltd.          USA
111  Double Decker Gift Stores, Ltd           UK
112            Diecast Collectables          USA
113               Kelly's Gift Shop  New Zealand

[114 rows x 2 columns]

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\3187916089.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

                          customerName      country  creditLimit
0           Australian Collectors, Co.    Australia     117300.0
1                    La Rochelle Gifts       France     118200.0
2         Mini Gifts Distributors Ltd.          USA     210500.0
3                 Blauer See Auto, Co.      Germany      59700.0
4                    Land of Toys Inc.          USA     114900.0
5               Euro+ Shopping Channel        Spain     227600.0
6               Saveley & Henriot, Co.       France     123900.0
7              Dragon Souveniers, Ltd.    Singapore     103800.0
8                   Muscle Machine Inc          USA     138500.0
9                Diecast Classics Inc.          USA     100600.0
10                Technics Stores Inc.          USA      84600.0
11                    Handji Gifts& Co    Singapore      97900.0
12                        Herkku Gifts     Norway        96800.0
13            Daedalus Designs Imports       France      82900.0
14           La Corne D'abondance, Co.       France      84300.0
15                     Gift Depot Inc.          USA      84300.0
16                Toys of Finland, Co.      Finland      96500.0
17                      AV Stores, Co.           UK     136800.0
18             Clover Collections, Co.      Ireland      69400.0
19               UK Collectables, Ltd.           UK      92700.0
20      Canadian Gift Exchange Network       Canada      90300.0
21                   Toys4GrownUps.com          USA      90700.0
22                Heintze Collectables      Denmark     120800.0
23        Collectable Mini Designs Co.          USA     105000.0
24                   giftsbymail.co.uk           UK      93900.0
25                  Amica Models & Co.        Italy     113000.0
26                Auto Associés & Cie.       France      77900.0
27             Toms Spezialitäten, Ltd      Germany     120400.0
28   Royal Canadian Collectables, Ltd.       Canada      89600.0
29             Anna's Decorations, Ltd    Australia     107800.0
30                       Rovelli Gifts        Italy     119600.0
31           Souveniers And Things Co.    Australia      93300.0
32                Marta's Replicas Co.          USA     123700.0
33                     Vida Sport, Ltd  Switzerland     141300.0
34                          Petit Auto      Belgium      79900.0
35                       Mini Classics          USA     102700.0
36                 Mini Creations Ltd.          USA      94500.0
37            Corporate Gift Ideas Co.          USA     105000.0
38                 Suominen Souveniers      Finland      98800.0
39             Classic Gift Ideas, Inc          USA      81100.0
40                  Reims Collectables       France      81100.0
41        Online Diecast Creations Co.          USA     114200.0
42               Salzburg Collectables      Austria      71700.0
43                 L'ordine Souveniers        Italy     121400.0
44             Tokyo Collectables, Ltd        Japan      94400.0
45                   Auto Canal+ Petit       France      95000.0
46  Bavarian Collectables Imports, Co.      Germany      77000.0
47             Scandinavian Gift Ideas       Sweden     116400.0
48                    Super Scale Inc.          USA      95400.0
49          Corrida Auto Replicas, Ltd        Spain     104600.0
50                    FunGiftIdeas.com          USA      85800.0
51                Diecast Collectables          USA      85100.0
52                   Kelly's Gift Shop  New Zealand     110000.0

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\3187916089.py:117: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

             customerName     amount
0  Euro+ Shopping Channel  120166.58

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\3187916089.py:201: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM student_details;", conn)

   student_id   name                email  age phone_number
0         101  Rahul  rahul_new@gmail.com   20   9876543210
1         102  Anita      anita@gmail.com   21   9876543211
2         103  Kiran      kiran@gmail.com   22   9876543212
3         104  Sneha      sneha@gmail.com   20   9876543213
4         105  Arjun      arjun@gmail.com   23   9876543214

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\3187916089.py:215: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM student_details;", conn)

   student_id   name                email  age phone_number
0         101  Rahul  rahul_new@gmail.com   20   9876543210
1         102  Anita      anita@gmail.com   21   9876543211
2         103  Kiran      kiran@gmail.com   22   9876543212
3         104  Sneha      sneha@gmail.com   20   9876543213

Database Connected Successfully

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\3187916089.py:233: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

                   customerName    country  creditLimit
0             Atelier graphique     France      21000.0
1            Signal Gift Stores        USA      71800.0
2    Australian Collectors, Co.  Australia     117300.0
3             La Rochelle Gifts     France     118200.0
4            Baane Mini Imports     Norway      81700.0
5  Mini Gifts Distributors Ltd.        USA     210500.0
6            Havel & Zbyszek Co     Poland          0.0
7          Blauer See Auto, Co.    Germany      59700.0
8               Mini Wheels Co.        USA      64600.0
9             Land of Toys Inc.        USA     114900.0

C:\Users\surya\AppData\Local\Temp\ipykernel_19120\3187916089.py:246: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

                               productName  buyPrice    MSRP  Estimated Profit
0    1969 Harley Davidson Ultimate Chopper     48.81   95.70             46.89
1                 1952 Alpine Renault 1300     98.58  214.30            115.72
2                    1996 Moto Guzzi 1100i     68.99  118.94             49.95
3     2003 Harley-Davidson Eagle Drag Bike     91.02  193.66            102.64
4                      1972 Alfa Romeo GTA     85.68  136.00             50.32
..                                     ...       ...     ...               ...
105                            The Titanic     51.09  100.17             49.08
106                         The Queen Mary     53.63   99.31             45.68
107              American Airlines: MD-11S     36.27   74.03             37.76
108                       Boeing X-32A JSF     32.77   49.66             16.89
109                             Pont Yacht     33.30   54.60             21.30

[110 rows x 4 columns]

In [ ]:
# Import NumPy

import numpy as np


# Problem 1

marks = [78, 85, 91, 67, 88]

arr = np.array(marks)

print(arr)
print(arr.dtype)
print(arr.shape)


# Problem 2

prices = [120, 450, 780, 220, 560]

arr = np.array(prices)

print(arr)
print(arr.ndim)
print(arr.size)


# Problem 3

scores = np.array([55, 60, 65, 70, 75, 80, 85, 90, 95, 100])

print(scores)
print(scores.shape)
print(scores.size)
print(scores.dtype)
print(scores.ndim)


# Problem 4

salary = [25000, 30000, 45000, 28000]

# Python List
updated_salary = []

for i in salary:
    updated_salary.append(i + 5000)

print(updated_salary)

# NumPy Array
salary_array = np.array(salary)

print(salary_array + 5000)


# Problem 5

marks = [60, 70, 80, 90, 95]

# Python List
new_marks = []

for i in marks:
    new_marks.append(i + 5)

print(new_marks)

# NumPy Array
marks_array = np.array(marks)

print(marks_array + 5)


# Problem 6

python_list = list(range(100000))

numpy_array = np.arange(100000)

print("Python List Created")
print("NumPy Array Created")

print(python_list[:5])
print(numpy_array[:5])


# Problem 7

fruit_prices = [20, 30, 40, 50]

print("Python List:", fruit_prices * 2)

fruit_array = np.array(fruit_prices)

print("NumPy Array:", fruit_array * 2)


# Problem 8

stock = [100, 200, 300, 400]

print("Python List:", stock * 2)

stock_array = np.array(stock)

print("NumPy Array:", stock_array * 2)


# Problem 9

expenses = [12000, 15000, 18000, 10000]

print("Python List Total:", sum(expenses))

expense_array = np.array(expenses)

print("NumPy Total:", np.sum(expense_array))
# Problem 10

marks = np.array([55, 65, 75, 85, 95])

print("First Element:", marks[0])
print("Last Element:", marks[-1])
print("Third Element:", marks[2])


# Problem 11

sales = np.array([120, 130, 140, 150, 160, 170])

print("First Three:", sales[:3])
print("Last Two:", sales[-2:])
print("Middle Values:", sales[2:4])


# Problem 12

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("First Row:", matrix[0])
print("Second Column:", matrix[:, 1])
print("Last Row:", matrix[-1])


# Problem 13

marks = np.array([35, 55, 72, 89, 40, 91])

print(marks[marks >= 40])


# Problem 14

salary = np.array([35000, 45000, 52000, 61000, 48000, 75000])

print(salary[salary > 50000])


# Problem 15

temperature = np.array([25, 28, 31, 35, 27, 40, 29, 33])

print(temperature[temperature > 30])


# Problem 16

ratings = np.array([2, 5, 4, 3, 5, 1])

print(ratings[[0, 2, 5]])


# Problem 17

books = np.array([
    "Python",
    "Java",
    "C",
    "C++",
    "SQL",
    "AI"
])

print(books[[1, 3, 4]])


# Problem 18

scores = np.array([45, 60, 55, 80, 75, 90, 85])

print(scores[[0, 3, 6]])